### ISSUE TITLE
uncaughtException: TypeError: main.server.enableRatelimiting is not a function

### ISSUE THREAD

**Issue by beck24** [highcharts/node-export-server#10]
When trying to ensure rate limiting is not set:

forever start ./node-export-server/bin/cli.js --enableServer 1 --rateLimit 0

> uncaughtException: TypeError: main.server.enableRatelimiting is not a function
>     at Object.<anonymous> (/home/ubuntu/highcharts-server/node-export-server/bin/cli.js:162:21)

**Comment by beck24** [comment]
The reason I'm trying to ensure rate limiting is not set is that we're generating pdfs with charts in them, and each pdf has 11 charts, but we're finding that after the first pdf generated any subsequent pdfs generated in a short amount of time fail with a connection timeout.  I can't find any reason for this so thought it may be that rate limiting is on by default.  Any suggestions would be welcome.

**Comment by cvasseng** [comment]
Hi, 

the rate limiter is disabled by default. If you're experiencing timeouts it's likely caused by something else. Have you tried enabling full logging (`--logLevel 4`) to see if there are any errors on the subsequent exports?

I fixed the `uncaughtException` in 0df09c6, but setting `--rateLimit 0` will effectively do nothing as it's already disabled by default.

**Comment by beck24** [comment]
I'm not sure what was going on, but this hasn't been happening lately.  Closing for now.
