### ISSUE TITLE
Generate with custom size

### ISSUE THREAD

**Issue by mr-nicky** [highcharts/node-export-server#111]
How to generate chart with specific sizes (without scale, as is). For example, we need to get chart with height 2000px and width 8000px. Just like we can archive this via browser implementation:

`<div id="container" style="height: 2000px; min-width: 8000px"></div>`

**Comment by dennisat** [comment]
According to the documentation only the `width` is supported, the `height` is missing... this is really strange! Please highcharts/node-export-server provide some help here.

**Comment by dennisat** [comment]
I found a way to do this.

Do not apply `width` in the options for the server, but define the exact dimension in the options of the chart.

At the end, the data you send to the server should be something like this:
```
"infile": {
  "chart": {
    "width": 557,	 // define here the width
    "height": 334,   // ... and height (but only here)
    "type": "line",
    "spacing": [
      0,
      0,
      0,
      0
    ],
```
Will be nice to document it some how because this `width` option is confusing.
Or the `height` should be there too where will override the chart's values.

**Comment by cvasseng** [comment]
The  `width`/`height` can also be set through `exporting.sourceHeight` in the chart config to make it separate from the actual chart size. See [here](https://api.highcharts.com/highcharts/exporting.sourceHeight).

I will add both to the readme.
