### ISSUE TITLE
Annotation support?

### ISSUE THREAD

**Issue by mark5280** [highcharts/node-export-server#121]
I've been running my own export server for some time and would like to add annotations.  If I attempt to render the same chart as https://jsfiddle.net/mark5280/x4xs6nhv/ (note the sample label in the upper left corner) using my export server the annotation (label) is not rendered in the upper left as expected.  

I know that using JSFiddle I have to include annotations.js.  Is there an equivalent for this with an export server?  

Thank you!

**Comment by cvasseng** [comment]
If you want to include additional modules, you need to clone the repository rather than installing the server from npm.  

Specifically, you need to clone and then:
1) add the scripts to the `cdnScriptsOptional` object in `build.js` (follow the same pattern as the entries already in there)
2) run npm install
3) run npm link if you want to point the global `highcharts-export-server` to your local repo copy

**Comment by mark5280** [comment]
Excellent!  Thank you for the help.

**Comment by cvasseng** [comment]
Sure thing!
