### ISSUE TITLE
Formatter function support?

### ISSUE THREAD

**Issue by mark5280** [highcharts/node-export-server#122]
I apologize for my 20 questions of late but I've not found a means to address passing a formatter function into a node-export-server since it is in json.  

I'd like to control some label formatting to include a unit of measure.  Is the preferred method of doing this to write the function in javascript and then include it server side using build.js or is there a different method recommended that can be used when calling the server?

Thanks for your help!

**Comment by cvasseng** [comment]
Currently the only way of doing this if you're using the export server as a node module is to stringify your option structure as JavaScript rather than JSON before passing it to the export function.

If you're using POST requests to the server, skip the quotes for property names without white spaces in them, and it should just work as it will then be treated as JavaScript. 

e.g. 
```
{
   "chart": {...}
}
```

vs.

```
{
   chart: {}
}
```

If you have your stuff unquoted as in the latter example, formatters should work fine.

This will be improved when we make the switch to Chrome Headless.

**Comment by vikassaklecha** [comment]
I'm trying to use it as node module and trying to generate chart, tried to use formatter function for legend, but does not seem to work. Even tried legendFormatter function does not work. Am I missing something?

`
var settings = {
    chart : {
         legend : {
             formatter : function() { console.log("not coming here!!!"); }
        }
    }
}

chartExporter.export(settings, function (err, res) {

}
`

**Comment by cvasseng** [comment]
As mentioned above, the only workaround when using it as a module is to write a stringily function yourself that sends converts you options structure into JavaScript (not JSON).

e.g.
```
chart.export('{ chart: { legend: {formatter: function () {}}}');
```
will work. Notice that the options is a string, the lack of quoting, and that the function is not a string - i.e. the options passed to export is a string containing proper JavaScript, not JSON.

**Comment by vikassaklecha** [comment]
thanks @cvasseng for the pointer, to save others, here is a work around used to stringify as a javascript.
Using JSON.stringify on the object will removes any function inside so used [this](https://gist.github.com/cowboy/3749767)

**Comment by cvasseng** [comment]
Thanks for sharing your workaround!

**Comment by c0decharlie** [comment]
Hey, I have the same problem as @vikassaklecha. I was trying to use your workaround but it doesn't work for me. Also I was trying to use `foramtter` in `callback` function. But that's not working too.
```javascript
{callback: 'function(chart) { chart.legend.labelFormatter = function() { return "x" + this.name} }'}
```
@cvasseng any idea how to make it work?

**Comment by apptio-milarsen** [comment]
Is there any upcoming action on this issue? I have a pretty complicated formatting function that makes use of a couple external libraries, so it can't be passed as stringified javascript.

**Comment by OzanKurt** [comment]
Did anybody solve this problem yet?

**Comment by jakubSzuminski** [comment]
Apologies for the late response.

You can add `formatter` functions in the `callback` function via the `--callback` option (https://github.com/highcharts/node-export-server#command-line-arguments).

Here's a corresponding Highcharts client-side code: https://github.com/highcharts/node-export-server#command-line-arguments

@c0decharlie the code you've included does not work, because you need to update the legend (`chart.legend.update({ labelFormatter: newLabelFormatterFunction`).

Setting the formatter with `chart.legend.labelFormatter = ...` will not work.

I encourage you to try out our latest Puppeteer-based version of the Export Server (here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information).

**Comment by lgcxc** [comment]
> I'm trying to use it as node module and trying to generate chart, tried to use formatter function for legend, but does not seem to work. Even tried legendFormatter function does not work. Am I missing something?
> 
> `var chartExporter = require('highcharts-export-server');` `var settings = { chart : { legend : { formatter : function() { console.log("not coming here!!!"); } } } }` `chartExporter.export(settings, function (err, res) { }`
> 
> Also tried, but no luck with formatters `var settings = { chart : { legend : { formatter : "function() { console.log("not coming here!!!")(); }" } } }`
> 
> @cvasseng @mark5280

You can implement it in another way. Let me give you a reference example：

```json
{
  "xAxis": {
    "categories": [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec"
    ]
  },
  "plotOptions": {
    "series": {
      "dataLabels": {
        "enabled": true,
        "format": "{point.formattedValue}"
      }
    }
  },
  "series": [
    {
      "data": [
        {
          "y": 1322,
          "formattedValue": "1.3K"
        },
        {
          "y": 1722,
          "formattedValue": "1.7K"
        },
        {
          "y": 2322,
          "formattedValue": "2.3K"
        },
        {
          "y": 3322,
          "formattedValue": "3.3K"
        }
      ],
      "type": "line"
    }
  ]
}
```

Go to this website(https://export.highcharts.com/) to test the above json，the results are as follows：

<img width="1623" alt="image" src="https://github.com/highcharts/node-export-server/assets/15682051/4bb3f709-5c8b-40e7-94e1-f47fa7e5fda3">
