### ISSUE TITLE
Silent install of node-export server

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/node-export-server#146]
#### Actual behaviour
It seems that when installing node-export server silently, environment variables HIGHCHARTS_USE_MAPS and HIGHCHARTS_USE_STYLED evaluate always to true.

#### Suggested solution
Replace:

```
embedAll(process.env.HIGHCHARTS_VERSION || 'latest',
  process.env.HIGHCHARTS_USE_STYLED || true,
  process.env.HIGHCHARTS_USE_MAPS || true,
  process.env.HIGHCHARTS_MOMENT || false
);
```

with:

```
embedAll(process.env.HIGHCHARTS_VERSION || 'latest',
  affirmative(process.env.HIGHCHARTS_USE_STYLED),
  affirmative(process.env.HIGHCHARTS_USE_MAPS),
  affirmative(process.env.HIGHCHARTS_MOMENT)
);
```

**Comment by cvasseng** [comment]
Thanks for reporting, I've committed a fix.

We need the defaults so we don't break backwards compatibility (for the public server especially), so implemented it a bit differently.

**Comment by rfboykin** [comment]
Hi, this fix still has an issue:

`process.env` will always be a string, so if attempting to use `HIGHCHARTS_INCLUDE_STYLED=0`, `includeStyled` will always evaluate to true within the if statement. 

A workaround currently is to define it as `HIGHCHARTS_INCLUDE_STYLED=''`, but I don't believe this is the expected behavior. 

I can put in another ticket if that is preferred.
