### ISSUE TITLE
Issues with json infiles that contain functions

### ISSUE THREAD

**Issue by jb3-2** [highcharts/node-export-server#16]
Hi, I would like to use json infiles that contain functions, e.g. for formatting labels. It seems that currently this is not possible, I get the following error when exporting to svg: 

`uncaughtException: [TypeError: Cannot read property 'trim' of undefined]`

I use [this](https://github.com/statabs-test/indikatoren/blob/master/charts/configs/portal/4128.json) chart config file and call the exporter via node as you stated [here](https://github.com/highcharts/node-export-server#using-as-a-nodejs-module). If I remove the functions, everything works fine. 

On export.highcharts.com, however, the chart is rendered correctly. Thanks for your help!

**Comment by cvasseng** [comment]
Hi,

Are you passing the options directly to the export-function as an instanced object, or loading it from file first?

Functions are not completely supported when running as a node module. That said, I've made some tweaks, and added a sample that contains functions, and use the server as a node module [here](https://github.com/highcharts/node-export-server/blob/master/tests/module/module_test.js). This seems to be working fine.

Please let me know if you're still having issues after updating your copy of the server to the latest one.

**Comment by jb3-2** [comment]
Hi, that is now working great using the server as a node module, thank you very much!

**Comment by cvasseng** [comment]
Getting functions to work properly when using as a node module and passing instanced objects to the export function is non-trivial, which, along with keeping the options as valid JSON, is why it's not supported (or rather, the support ends at "it won't produce syntax errors, but functions are effectively ignored").

As of aad1a5a you can add custom formatters by using the `customCode` option in module mode, which is a function executed before initializing the chart where the options can be mutated:
    
    var exportSettings = {
            options: {
                //Options goes here
            },
            customCode: function (options) {
                // Functions can be added here too
                options.title = { 
                    text: 'Changed through custom code!'
                };
            }
        };
       
       // init code here
        
       exporter.export(exportSettings, ..);

A full sample can be found [here](https://github.com/highcharts/node-export-server/blob/master/tests/module/module_test.js).

I've also added JavaScript support to the `infile` option, so functions should work as expected when using that now (`infile` attribute when using as a node module, `--infile` when using through CLI. Expects the argument to be a filename). 

If you need to pass in formatter functions etc. in the options themselves the best way is to run the server in HTTP mode, which is what export.highcharts.com is doing. In HTTP mode, the input is treated the same as with `--instr` (and now `--infile`), which injects the options into phantom as JavaScript and not JSON (this is largely done for legacy reasons - ideally the export server would only support JSON as there's a lot of additional magic that needs to be done for the inject to work, and the dataOptions/globalOptions/customCode/resources arguments can handle the use cases where e.g. functions are necessary).

**Comment by bronius** [comment]
I'm trying to follow along and am also running into issues with references to `this` in formatter javascript functions.  It's not clear to me: When generating via curl/http, is using the above-referenced build and `customCode` the /only/ way to do it, or should it still work with latest stable but maybe with what alterations?

Ex (from PHP, pre-JSON).
`      "tooltip" => array(
        "formatter" => "function() {
          return '' + this.series.name +' zone: '+ Math.abs(this.y) +'$suffix';
        }"
      ),`

**Comment by bronius** [comment]
I appreciate the discussion and work here and am trying to follow along..  Awesome work!
I am rendering charts via curl/http on my locally hosted highcharts-export-server but am generating chart options as json from a PHP array (json_encode).  I couldn't figure out how to eval the javascript functions (as OP above), but I found that customCode is working for me ok.
In the discussion above, it was advised to use customCode for node module but that original pojo options should work via curl/http.  Is there a recommended way to load eval'able functions into the json options payload?

**Comment by cvasseng** [comment]
@bronius: If you pass in JavaScript instead of JSON, things should "just work" over HTTP.

e.g. this will be interpreted as straight up JavaScript:
    
    {
        chart: {}
    }

while this will be passed into JSON.parse:
    
    {
        "chart": {}
    }

You can see this by going to [the official server](http://export.highcharts.com), and entering pure JavaScript into the options text area.

**Comment by bronius** [comment]
Hi @cvasseng - I have been trying a number of different iterations, discovering that my original copy/paste source had TABs instead of spaces in some places, nuances of " vs ', etc.  I thought I'd take it to the basics and tried submitting the http code sample from the docs as javascript:
`curl -H "Content-Type: application/json" -X POST -d "
  {title: {text: \"Steep Chart\"}, xAxis: {categories: [\"Jan\", \"Feb\", \"Mar\"]}, \"series\": [{data: [29.9, 71.5, 106.4]}]}
" 10.0.2.2:7801 -o /var/host/chart.png`
No dice.  I tried keeping the "infile" and the opening brace as well.  How would you rewrite that same as javascript to demonstrate your response that js will be interpreted as js and json as json?   I also tried sending application/javascript instead of json, no dice..  :-/

Thanks

**Comment by cvasseng** [comment]
Glad you got it working.

For reference, the POST valid arguments/format is documented [here](https://github.com/highcharts/node-export-server#http-server).

I'm closing this since it seems like it's working for you now. Please feel free to re-open this if you have any further issues with it.

Thanks.
