### ISSUE TITLE
Can't install highcharts server.

### ISSUE THREAD

**Issue by majidhassan** [highcharts/node-export-server#18]
Hey,

I had previously been able to install the highcharts-export-server. Today, I tried to install using the commands mentioned [here](https://github.com/highcharts/node-export-server#install).

I've added the complete stacktrace below. Let me know if I'm doing anything wrong.

```
> phantomjs-prebuilt@2.1.14 install /home/parse/node-export-server/node_modules/phantomjs-prebuilt
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/parse/node-export-server/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.7.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/parse/node-export-server/npm-debug.log
```

**Comment by jb3-2** [comment]
Hi, I've had similar issues in the past. In my case, it always helped deleting the whole "node_modules" directory, then reinstalling the package using `npm install highcharts-export-server -g`. Hope that helps.

**Comment by edgarrenza** [comment]
Hello, I've had similar issues, but the log says: Cannot find module 'asn1' ... so I installed that module ( npm install asn1 ), but then I got this error: Cannot find module 'async'... In the same way I installed that module ( npm install async ) and ran perfectly... following that logic, install that module ( npm install is-property )

**Comment by cvasseng** [comment]
@majidhassan: It looks like you've stumbled across an issue with [one of the dependencies](https://github.com/Medium/phantomjs/issues/654). Based on the issue over there, the error seems to have been introduced in a commit on 9th of December when a few of their dependencies were updated. It looks like it only happens on certain configurations. 

If you're installing as a dependency of your own application (e.g. you're using it as a module), you could try deleting `node_modules` as proposed by @jb3-2, run `npm cache clean`, and finally `npm install` again. If you're installing globally with npm, try `npm cache clean` and then a reinstall. What @edgarrenza said will also likely work (manually install the `is-property` package), but that may or may not lead to other similar issues. I'll look into changing our package.json to use phantom-prebuilt 2.1.13 instead, but that version has several very old dependencies, so other things may not work ideally.

@edgarrenza: could you post a full output of your NPM log?

**Comment by majidhassan** [comment]
@cvasseng I went with installing the `is-property` package and ended installing several other packages till I was able to install highcharts. Here's the list of packages I had to install to get it to work:

`npm install -g is-property generate-object-property generate-function jsonpointer xtend`

then I ran `npm install -g highcharts-export-server`.

**Comment by edgarrenza** [comment]
@cvasseng The log of that day I do not have it, but I did a test and tried to install highcharts-export-server in a new project, but this time this error appeared:


gustavo@gnr-WEB:~/Desa10/Proyectos/PruebaHighchart$ npm install highcharts-export-server
 
> phantomjs-prebuilt@2.1.14 install /home/gustavo/Desa10/Proyectos/PruebaHighchart/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/gustavo/Desa10/Proyectos/PruebaHighchart/node_modules/highcharts-export-server/node_modules/request/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/home/gustavo/.nvm/versions/node/v4.5.0/bin/node" "/home/gustavo/.nvm/versions/node/v4.5.0/bin/npm" "install" "highcharts-export-server"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gustavo/Desa10/Proyectos/PruebaHighchart/npm-debug.log

/***************** this is other test *******************************/

gustavo@gnr-WEB:~/Desa10/Proyectos/PruebaHighchart$ npm install highcharts-export-server
-
> phantomjs-prebuilt@2.1.14 install /home/gustavo/Desa10/Proyectos/PruebaHighchart/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/gustavo/Desa10/Proyectos/PruebaHighchart/node_modules/highcharts-export-server/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/home/gustavo/.nvm/versions/node/v4.5.0/bin/node" "/home/gustavo/.nvm/versions/node/v4.5.0/bin/npm" "install" "highcharts-export-server"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gustavo/Desa10/Proyectos/PruebaHighchart/npm-debug.log


/***************** this is other test *******************************/


gustavo@gnr-WEB:~/Desa10/Proyectos/PruebaHighchart$ npm install highcharts-export-server
> phantomjs-prebuilt@2.1.14 install /home/gustavo/Desa10/Proyectos/PruebaHighchart/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/gustavo/Desa10/Proyectos/PruebaHighchart/node_modules/highcharts-export-server/node_modules/request/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/home/gustavo/.nvm/versions/node/v4.5.0/bin/node" "/home/gustavo/.nvm/versions/node/v4.5.0/bin/npm" "install" "highcharts-export-server"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gustavo/Desa10/Proyectos/PruebaHighchart/npm-debug.log




/***************** this is other test *******************************/


gustavo@gnr-WEB:~/Desa10/Proyectos/PruebaHighchart$ npm install highcharts-export-server
 
> phantomjs-prebuilt@2.1.14 install /home/gustavo/Desa10/Proyectos/PruebaHighchart/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'asn1'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/gustavo/Desa10/Proyectos/PruebaHighchart/node_modules/highcharts-export-server/node_modules/request/node_modules/http-signature/node_modules/sshpk/lib/formats/pem.js:9:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/home/gustavo/.nvm/versions/node/v4.5.0/bin/node" "/home/gustavo/.nvm/versions/node/v4.5.0/bin/npm" "install" "highcharts-export-server"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gustavo/Desa10/Proyectos/PruebaHighchart/npm-debug.log



The problem is random, as I can see it fails for different modules that you need to perform the installation and that for some reason does not install by itself.

**Comment by cvasseng** [comment]
We're unable to reproduce this on OSX, CentOS, Amazon Linux, and Ubuntu. 

Judging from the logs, it looks to be an issue with phantom-prebuilt as mentioned previously, or in one of their dependencies. We will change the version we use to 2.1.13 rather than the latest, as it seems like the issue was introduced in 2.1.14 when they changed their package file. Hopefully that will resolve the issue.

We will push this change to NPM and Git tomorrow, as we want to run some quick tests first to make sure nothing else is breaking.

**Comment by cvasseng** [comment]
I'm assuming this is fixed given the silence for over a month.

If any of you experience more issues like this, please feel free to reopen this issues, or to create a new one.

**Comment by arisliang** [comment]
i'm still having issue when installing export server. Not sure if it's the same issue though...

Error message:
**********************
Error making request.
Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
**********************
OS: windows 10
npm: 5.4.2

**Comment by cvasseng** [comment]
We had to go back to 2.1.4 due to memory issues with 2.1.3. 

If you can't get it to work, please try cloning the repository and changing it to `2.1.3` in `package.json` and run `npm install && npm link`.

**Comment by arisliang** [comment]
Thanks, my issue was proxy related, after sort that out, npm installed successfully without changes.
