### ISSUE TITLE
Problem on run in Heroku

### ISSUE THREAD

**Issue by richellyitalo** [highcharts/node-export-server#181]
When I ran the command on heroku `highcharts-export-server --enableServer 1 --host highcharts-server.herokuapp.com --port 8000`
Show the error:
Tue Dec 11 2018 13:35:27 GMT+0000 (Coordinated Universal Time) [error] socket error: { Error: listen EADDRNOTAVAIL: address not available 34.224.36.137:8000
    at Server.setupListenHandle [as _listen2] (net.js:1241:19)
    at listenInCluster (net.js:1306:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1445:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '34.224.36.137',
  port: 8000 }

Any solution to this?

**Comment by kreintjes** [comment]
On Heroku you must bind the server to the port specified in the PORT ENV variable by Heroku. Otherwise it will not work.So setting the port manually to 8000 probably also doesn't work. See: https://devcenter.heroku.com/articles/deploying-nodejs#specifying-a-start-script

Also setting the host manually isn't needed (and might interfere with running the export server on Heroku as well).

So try to replace your start command with: `highcharts-export-server --enableServer 1 --port $PORT`.
