### ISSUE TITLE
Export server doesn't support Wordcloud series

### ISSUE THREAD

**Issue by raf18seb** [highcharts/node-export-server#195]
#### Actual behaviour
There is a missing module in build.js file and export server throws an error 17 while exporting Wordcloud series type. 

#### Reproduction steps
JSON config:
```
{
  "chart": {
    "type": "wordcloud"
   },
     
   "series": [{
     "data": [{"name": "Sample"}]
   }]
}
```

**Comment by KacperMadej** [comment]
@raf18seb 
When installing the server have you answered with `y`/`yes` on prompt about the wordcloud series?
Maybe used Highcharts core version is not compatible with the module? (should happen only with old versions of Highcharts - before the wordcloud was added)

**Comment by raf18seb** [comment]
Yes, I have. Thanks for pointing this - now I can see that it works fine with node export server.
The issue occurs with https://export.highcharts.com/ server. Is there a separate repo for it?

**Comment by runov001** [comment]
How to make the word cloud export working when using highcharts with automatically deployed version?

**Comment by KacperMadej** [comment]
@runov001 
Please specify what do you mean by `automatically deployed version`.
If the error 17 shows up, then series is not recognized - this might be caused by lack of the module(s) required by the series used or by a typo in series type in chart options. Please check both - server configuration and installation and used chart configuration.

**Comment by vste23** [comment]
@KacperMadej `automatically deployed version` means that CI system is building this package, and CI system can't answer question by setting y/n. In order to overcome this problem we uses env variables. Problem, is that we don't have env variables to set optionals, like wordcloud package. There is a fork that fixes it if you are interested https://github.com/highcharts/node-export-server/issues/142

**Comment by jakubSzuminski** [comment]
It has been solved and it's possible to export the `WordCloud` series now:
- try to export here: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/wordcloud
- test this out https://export.highcharts.com/ with the following config: `{
    "series": [
        {
            "data": [{"name":"aa"}],
            "type": "wordcloud"
        }
    ]
}`
- locally, it works as well when you select "yes" during build (there is no environement variable for this, but this will not be a problem in the new `puppeteer` version)
