### ISSUE TITLE
Get PNG as file output instead of base64

### ISSUE THREAD

**Issue by azizj1** [highcharts/node-export-server#219]
I'd like to get an output of a chart as PNG file, but it is always returned as base64 in `res.data`. I also don't see any options to do it as a file, and `outfile` param did nothing.

Thanks!

**Comment by jakubSzuminski** [comment]
Thanks for reporting and apologies for the late response.

I think what you're referring to is the `b64` option which can be used in the HTTP server request body: https://github.com/highcharts/node-export-server/tree/master#http-server which did not seem to work for a long time.

Fortunately, it has been fixed in the latest Puppeteer-based version which I encourage you to try out (here's a [short setup guide](https://github.com/highcharts/node-export-server#puppeteer-version-information)).

If you encounter any problems in the newest version please report them and we will investigate them.
