### ISSUE TITLE
Used as a node module, export doesn't run functions

### ISSUE THREAD

**Issue by soetji** [highcharts/node-export-server#227]
#### Expected behaviour

Functions like `tickPositioner` and `formatter` are not executed.

#### Actual behaviour

They should be executed.

#### Reproduction steps
 

Call `exporter.export()` with the following options.
```
const exportOptions = {
    type: 'png',
    options: {
        {
            "text": "Steep Chart"
        },
        "series": [
            {
                "data": [
                    29.9,
                    71.5,
                    106.4
                ]
            }
        ],
        "yAxis": [
                {
                    "tickPositioner": function () {
                        return [0, 1, 10, 50, 250];
                    }
                }
            ]
        }
    }
}
```

**Comment by KacperMadej** [comment]
Hi @soetji 

Please add a live demo of the problem.

**Comment by kmannislands** [comment]
Not a bug per say so much as an architectural challenge with this library.
There doesn't seem to be anything related to custom serialization of the options passed in. They are simply [JSON stringified](https://github.com/highcharts/node-export-server/blob/88dc52a6ae2819f980b1a2bb99bc92f4f09f06c8/lib/phantompool.js#L264) to pass in to the phantom worker thread. 
@soetji as a work around, you can try using something like [serialize-javascript](https://www.npmjs.com/package/serialize-javascript) and supply your options as `instr` instead of `options` when you call `export()`. Just be careful with scope

**Comment by ProtonGustave** [comment]
@soetji you can use this lib https://github.com/ProtonGustave/charts-rendering for this.

**Comment by jakubSzuminski** [comment]
You can use the `--callback` argument (https://github.com/highcharts/node-export-server#command-line-arguments) to add a function which adds JavaScript functions to the chart (formatter, positioner, etc.)

Here's a corresponding Highcharts client-side code: https://jsfiddle.net/BlackLabel/usjynqkf/

I encourage you to take a look at our latest puppeteer version (here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information).
