### ISSUE TITLE
Overriding Highcharts log functions in export server

### ISSUE THREAD

**Issue by h11a** [highcharts/node-export-server#248]
I am trying to get a chart exported using the http server with a negative log scale. The example I am trying is from here 

https://www.highcharts.com/blog/snippets/alternative-maths-plotting-negative-values-logarithmic-axis/ 

and works fine in the browser but I can't find a way of overriding the log scale in npm.

e.g. this part 
```
(function (H) {
    // Pass error messages
    H.Axis.prototype.allowNegativeLog = true;

    // Override conversions
    H.Axis.prototype.log2lin = function (num) {
        var isNegative = num < 0,
            adjustedNum = Math.abs(num),
            result;
        if (adjustedNum < 10) {
            adjustedNum += (10 - adjustedNum) / 10;
        }
        result = Math.log(adjustedNum) / Math.LN10;
        return isNegative ? -result : result;
    };
    H.Axis.prototype.lin2log = function (num) {
        var isNegative = num < 0,
            absNum = Math.abs(num),
            result = Math.pow(10, absNum);
        if (result < 10) {
            result = (10 * (result - 1)) / (10 - 1);
        }
        return isNegative ? -result : result;
    };
}(Highcharts));
```

Highcharts is undefined and I am not sure if the after init will even work...

I have experimented with the callback param you can provide but no luck with that either. 

Sidenote - Is there any easy way of getting the console.logs to show in the callback? The only way I have found to debug it is to set the title of the chart with different strings... which is really bad.

**Comment by pawelfus** [comment]
Hi @h11a 

The code above won't work with new versions of Highcharts. Instead use this one: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/type-log-negative/

How to include? Use `resources` or `customCode` options. Try copying & pasting `(function (H) { ... })(Highcharts)` to a separate file, then include in resources.

Callback parameter can't be used, because it's called after chart is rendered. The plugin you want to use should be added before creating the chart.

I'm not sure if we can do anything about `console.log`, I might be wrong, but the code is passed on to phantomJS, which does not provide an option to overwrite `consoel.log`. Did you try for example `throw new Error()` ? This may work 🤔

**Comment by h11a** [comment]
Does resources need to be a json file? It seems to not like me passing the string function in

**Comment by pawelfus** [comment]
Resources should be JSON containing files info, not a string function. Use `customCode` for a function. If you ask the same question on SO and on our GH it would be nice to post link to each other. It's not me who is helping you on SO :)

**Comment by h11a** [comment]
Ah i saw pawel and just assumed, sorry xD I managed to get it working here is the link https://stackoverflow.com/questions/63343645/overriding-log-scale-with-highcharts-export-server/63375446?noredirect=1#comment112067045_63375446

**Comment by PaulDalek** [comment]
Hi @h11a,

I'm the one who's been helping you on SO :). Although my answer works in your case, it's far from perfect. As @pawelfus mentioned, the callback approach is not a very good idea as the event is added after the chart creation (hence the necessity of updating the `yAxis` to the `logarithmic` type after in my answer). The solution regarding using the resources file is much better and universal. I have updated my SO answer by including this approach (https://stackoverflow.com/questions/63343645/overriding-log-scale-with-highcharts-export-server/).
