### ISSUE TITLE
Is it possible to get a proper error response from the command line rendering?

### ISSUE THREAD

**Issue by Pi-George** [highcharts/node-export-server#262]
If a bad command is executed such as `$ highcharts-export-server -instr {"ahojadw": "ojiawd'test'"} -outfile here.png` where the parsing will fail for the instr. You'd normally expect to get an error message and a non-zero response code back from the terminal. Instead the image itself has the "Chart input data error". This makes it impossible to know if the image has a problem or not without checking it yourself, which of course doesn't work as a solution when automating chart generation.

Equally problematic is the handling of commands such as `$ highcharts-export-server -infile ahjsdoiajwd -outfile joaijwd` which seem to just hang and the command will never complete.

**Comment by PaulDalek** [comment]
Hi @Pi-George

Thank you for reporting this issue and proposing this enhancement for better error handling. Setting the value of the `instr` the way you do in the example (like this `{"ahojadw": "ojiawd'test'"}`) will treat it as two different arguments. In a result at some points the `instr` will have a value equal to '{ahojadw:' instead of the correct stringified chart options, therefore it won't be correctly parsed to JSON. That's the reason for placing the whole value in the string. You could get rid of the string notation but you must be sure that there are no white spaces in the value (so for example this will work `{\"series\":[{\"data\":[1,2,3]}]}`). Also, even if the structure is a JSON format, it’s up to user to make sure it contains correct chart options.

**Comment by Pi-George** [comment]
Hi @PaulDalek that was just an example of a bad command. My question itself is about getting response codes and error messages as well as the hanging commands.

**Comment by Pi-George** [comment]
@PaulDalek any advice? I'd like to set up highcharts so that I can create charts on demand on the backend rather than hosting a highcharts server that I can't scale. But if any errors experienced will be shown to the users in the form of an image of the error text or if it starts to cause timeouts then it seems like a rather large problem.

**Comment by PaulDalek** [comment]
@Pi-George

By my previous comment I rather meant that the value for the `instr` parameter in such a form won’t work as it will be treated as two arguments. As for now, in case of an incorrect data input, instead of a chart, the error is placed in a containing div (see the `worker.js` file). I marked the issue as an enhancement, so we can think of a better solution for such situations.

**Comment by jakubSzuminski** [comment]
We'll be working on improving error handling in the latest Puppeteer-based version, here's a new issue for this: https://github.com/highcharts/node-export-server/issues/409

---
I encourage you to try out the Puppeteer-based version of the Export Server. Here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information

Please feel free to report any problems you encounter with the newest version and we will investigate it.
