### ISSUE TITLE
Export to SVG doesn't work

### ISSUE THREAD

**Issue by cojack** [highcharts/node-export-server#285]
#### Expected behaviour
Should export SVG

#### Actual behaviour

Hangs out

#### Reproduction steps
 

Open `tests/basic.json` add `"type":"svg"` run tests

**Comment by madepiet** [comment]
From what I tested here, exporting to SVG works fine:
https://export.highcharts.com/

Could you please check this and provide more information on how you are doing this query to the server?

Remember to take care of the proper configuration of the JSON object:
`{"xAxis":{"categories":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},"series":[{"data":[1,3,2,4],"type":"line"},{"data":[5,3,4,2],"type":"line"}]}`

**Comment by cojack** [comment]
```
diff --git a/tests/basic.json b/tests/basic.json
index 40a9e9d..11d8986 100644
--- a/tests/basic.json
+++ b/tests/basic.json
@@ -1,4 +1,5 @@
 {
     "constr": "Chart",
+    "type": "svg",
     "options": {"xAxis":{"categories":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},"series":[{"data":[1,3,2,4],"type":"line"},{"data":[5,3,4,2],"type":"line"}]}
-}
\ No newline at end of file
+}
```
then run tests: `node tests/run.js` server hangs

**Comment by dryhumor** [comment]
### Problem
Our SVG exports started failing recently on Heroku. They were working fine, then we deployed code on 2021-06-07, and they've been failing since then. The code changes had nothing to do with highcharts.

### Cause
When we deployed, highcharts 9.1.1 had recently become the latest version. We didn't have `HIGHCHARTS_VERSION` set, so the build pulled in 9.1.1, which seems to have introduced bugs. As @cojack noted, SVG exports hang. Without the addition of `"type": "svg"`, the basic.json test still fails:

`Test basic.json failed: an error occured when rendering the chart: SyntaxError: Unexpected token R in JSON at position 0`

### Solution
Specifying a different version (in our case, 8.2.0) fixed it:

On my machine, this worked:

1. `npm rebuild`
2. for the prompt `Agree to the license terms? y/n:  (no)`, enter `y`
3. for the prompt `Select your Highcharts version (e.g. 4.2.2)::  (latest)`, enter `8.2.0`

For our Heroku cloud servers, this worked:

1. `heroku plugins:install heroku-builds`
2. `heroku builds:cache:purge -a <app-name>`
3. `heroku config:set HIGHCHARTS_VERSION=8.2.0 -a <app-name>`
4. push to Heroku to trigger the build process

**Comment by jakubSzuminski** [comment]
I encourage you to try out our latest Puppeteer-based version of the Export Server (here’s a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information) where hopefully this issue does not occur anymore.

If this issue still persists in the newest version, please report it again so we can investigate it.
