### ISSUE TITLE
Server does not render labels with HTML formatting

### ISSUE THREAD

**Issue by jaredculp** [highcharts/node-export-server#294]
#### Expected behaviour

The correct behavior is seen on https://export.highcharts.com with the following input:
```json
{"xAxis":{"categories":["<b>A</b>","B"]},"series":[{"data": [1, 2]}]}
```

![](http://export.highcharts.com/charts/chart.a7cce71ff00648bdbee15570adda426b.png)

#### Actual behaviour

When running the export server locally (server=2.1.0, highcharts=9.1.0), labels are not bolded:

#### Reproduction steps

```bash
$ ./node_modules/highcharts-export-server/bin/cli.js --enableServer --logLevel 4 --port 8080 --allowCodeExecution 1 &
$ curl -H "Content-Type: application/json" -X POST -d '{"infile":{"xAxis":{"categories":["<b>A</b>","B"]},"series":[{"data": [1, 2]}]}}' "http://localhost:8080" -o out.png
```

**Comment by jaredculp** [comment]
It seems like this is only an issue exporting to png. Exporting to SVG works fine!

**Comment by KacperMadej** [comment]
Hello,

Thank you for reporting the problem.

We are currently in the middle of implementing some big changes for the export server - changing from outdated PhantomJS to Puppeteer. A beta version for testing is expected later this year. The transition is planned for Q4 2021 - Q1 2022.

Because of this, all minor fixes are placed on hold and will be picked up after the transition - in case the transition itself won't fix the problems. If the problem that you have currently is critical for security reasons it will be fixed right away, but other problems will have to wait a bit. While waiting we will be trying to suggest a workaround solution for you.

Thank you for your patience and understanding.

If a bold font is not showing correctly then it would suggest that the font family in the bold variant is not installed. Please try with a different font family or set it with some other font names as a fallback to confirm the problem source. If the export server on the official CDN is working then it might be using a preinstalled system font file that is not preinstalled on the machine you are using to run the server locally.

Exporting to SVG is producing SVG file that is using system fonts of the machine that opens the SVG to view it, so this would confirm the font being not installed. Installing fonts is explained here: https://github.com/highcharts/node-export-server#installing-fonts

The node export server version you are using is not current or the most up-to-date - please try updating the node export server.
