### ISSUE TITLE
b64=true is not returning response in base64 format, response is empty when b64 is set as true

### ISSUE THREAD

**Issue by kalandher** [highcharts/node-export-server#324]
#### Expected behaviour
Response type should be base64

#### Actual behaviour

![image](https://user-images.githubusercontent.com/24358595/151508980-8ebf97a5-1f33-41a1-8ff7-117bd2371413.png)

#### Reproduction steps
 

this is the input given for node server

```
{
    "type": "png",
    "b64":true,
    "options": {
        "title": {
            "text": "My Chart"
        },
        "xAxis": {
            "categories": ["Jan", "Feb", "Mar", "Apr", "Mar", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        },
        "series": [
            {
                "type": "line",
                "data": [1, 3, 2, 4]
            },
            {
                "type": "line",
                "data": [5, 3, 4, 2]
            }
        ]
    }
}

```

**Comment by noxify** [comment]
Hi @kalandher 

I had the same problem - Here the snippet how I solved it.

```json
{
    "infile": {
        //...
    },
    "b64": true,
    "noDownload": true,
}
```

**Comment by jakubSzuminski** [comment]
Thanks for reporting!

I've tested this out in our latest Puppeteer-based version of the Export Server and this issue is no longer a problem, the `b64` option works just as expected.

I encourage you to try the newest version out, here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information

Please feel free to report any problems you encounter with the newest version and we will investigate it.
