### ISSUE TITLE
script for automatic installation

### ISSUE THREAD

**Issue by poliveira89** [highcharts/node-export-server#37]
Installing this module with NPM `npm install -g highcharts-export-server` needs human interaction at the middle of the process:

When these questions appear:
```
Agree to the license terms? y/n:  (no)
Select your Highcharts version (e.g. 4.2.2)::  (latest)
Include Maps? (requires Maps license):  (no)
Enable styled mode? (requires Highcharts/Highstock 5 license):  (no)
```

I wonder if it's possible to automate these part to be installed within a fully automated script?

**Comment by cvasseng** [comment]
See the [section on automated deployments](https://github.com/highcharts/node-export-server#using-in-automated-deployments) in the readme.

The gist is that you can set the environment variables `ACCEPT_HIGHCHARTS_LICENSE`, `HIGHCHARTS_VERSION`, and `HIGHCHARTS_USE_STYLED` prior to running the install.

We likely won't offer any scripts to provide more automation that that, since we want user to manually agree to the license terms, either by answering yes during the install, or by setting the environment variable one way or another.

**Comment by poliveira89** [comment]
Those I suppose to be enough for an automated deployment. Thanks.
