### ISSUE TITLE
HTTP mode - use of batch and output file name

### ISSUE THREAD

**Issue by omkar1707** [highcharts/node-export-server#38]
How to use batch option and output file name with HTTP mode?

For below example outfile is not working.
{"infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}, "series": [{"data": [29.9, 71.5, 106.4]}]}
,"outfile":"graph","async":true}

**Comment by cvasseng** [comment]
Are you trying to produce files in the server filesystem? E.g. posting to the server, and then have the server produce the files on its local filesystem for later retrieval?

**Comment by omkar1707** [comment]
Yes..Right. I want to save file on the server.

**Comment by cvasseng** [comment]
The HTTP server is made to do the opposite, that is, saving the charts on the client rather than the server. I'd recommend [using the export server as a node module](https://github.com/highcharts/node-export-server/blob/master/tests/module/module_test.js) and writing your own batch setup if the CLI option isn't sufficient for your use case. 

That said, you could exploit the temporary saving mechanism to have it store things on the server but the temporary files are purged after 15 minutes. The path can be set using the `--tmpdir` option when you start the server. Then, if you use `async:true` in your post body, the charts will be saved in the folder specified - but only for 15 minutes; and you won't have any control over their filename.

**Comment by larsac07** [comment]
Closing this as it was answered
