### ISSUE TITLE
cannot loop trigger the exporting

### ISSUE THREAD

**Issue by wandiong** [highcharts/node-export-server#41]
i have an issue regarding of this

the code is
`// i want only 2 table this is as example
//Export settings 
var exportSettings = {
 type: 'png',
 options: {
 title: {
 text: 'My Chart'
 },
 xAxis: {
 categories: ["Jan", "Feb", "Mar", "Apr", "Mar", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
 },
 series: [
 {
 type: 'line',
 data: [1, 3, 2, 4]
 },
 {
 type: 'line',
 data: [5, 3, 4, 2]
 }
 ]
 }
};

//Set up a pool of PhantomJS workers

for(var i = 0; i < chart.length; i++) {
exporter.initPool();

//Perform an export
/*
 Export settings corresponds to the available CLI arguments described
 above.
*/
exporter.export(exportSettings, function (err, res) {
 chart[0].image = res.data
 console.log(i)
 exporter.killPool();
});
}
`
expectation : it should loop twice

reality : it just rendering final array data

anybody had an idea for this ?

**Comment by cvasseng** [comment]
There's issues with scoping in your code. The export call is async, meaning that `i` will always have the value of `chart.length - 1` when the export callback is executed, since the callbacks will be called after the loop is done iterating.

You should also only init the pool once, as it's global. In addition, you're killing the pool after the first export returns (in the `exporter.export` callback), effectively canceling the next export.

Try something like:
    
    var charts = [<array of charts meta>],
        chartResults = []
    ;
    
    exporter.initPool();
    
    charts.forEach(function (chart, i) {
        exporter.export(exportSettings, function (err, res) {
            console.log('did export', i);
            
            // Add the data to chartData
            chartResults.push(res.data);
        });
    });

This will leave the pool running. If you want to run `exporter.killPool` (or if you want to take any other action when all the exports have completed), you should look into either [Promises](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise), or [async](https://github.com/caolan/async).

**Comment by wandiong** [comment]
works great, I modified some part on it and it went as I expected. thanks a lot for helping and sorry for too long response .. totally appreciated !! 👍

**Comment by cvasseng** [comment]
No problem! Glad it worked out for you.

**Comment by miniil** [comment]
Hi,

Thanks for this but can you explain me or show me an example how to use Promise or async to take action when all the exports have been completed?

Thank you.
