### ISSUE TITLE
Global options with an svg as input

### ISSUE THREAD

**Issue by mcharnet** [highcharts/node-export-server#410]
Using both the phantom and the pupeeter versions, I encounter an issue with the server. I use it to get the base64 image from an svg thanks to a REST call. It's working well, except for the options. I would like to hide both the tooltip and the legend on the generated chart, but can't to achieve this. I tried setting `globalOptions` or `options`, but couldn't succeed. It seems to be OK on the demo app, but using an "infile" input with the chart as json, instead of an svg. 

Could you help me ? 

Thanks ! 

#### Expected behaviour

Being able to set chart options with an svg as input.

#### Actual behaviour

Options are not taking into account while generating the chart from an svg.

**Comment by jakubSzuminski** [comment]
Thanks for reporting @mcharnet!

Please, let me know if I understand you correctly.

1. You're sending an SVG to our Export Server and you're expecting a base64 back.
2. In the SVG that you're sending, there's a legend (just an example).
3. You also have `options: { legend: { enabled: false } }` specified in the request.
4. You're expecting the base64 to not have legend even though it exists in the SVG?

**Comment by mcharnet** [comment]
Hello @jakubSzuminski !

Thanks for your reply. 
It's exactly what I meant, you perfectly understood the issue. Could it be solved ?

**Comment by jakubSzuminski** [comment]
**The Export Server:**
-> accepts an SVG file and converts it to a different format (JPG/PNG/PDF)
-> or accepts a Highcharts config, renders the chart based on the Highcharts config, and returns an output in JPG/PNG/PDF/SVG

If you're sending an SVG, the options config is not taken into account, because we're not rendering a chart - we're just converting an SVG to a different format.

If you're sending a Highcharts config then the chart is rendered in the headless browser and you get the result of that render.

So, the current behavior is the desired behavior and I do not see any way to include the options when you're sending an SVG (to implement that we would need to have an SVG -> chart config converter and then: merge the chart config with the options, render a completely new chart based on the merged options and return it in a given format).

However, do not worry as I'll try to help you in your case. Could you please explain how do you get your SVGs? 

If you're using Highcharts with the _exporting.js_ module you can simply set the `exporting.chartOptions.legend.enabled: false` to achieve this: https://jsfiddle.net/BlackLabel/swvaLz4e/

**Comment by jakubSzuminski** [comment]
I'm closing this issue as it is not planned, but please feel free to ask for help in case you need anything!

**Comment by mcharnet** [comment]
Thank you for the explanation @jakubSzuminski. It confirms what I saw in the code.

I get the svg from my application. It is drawn as a full svg first, and we want to generate a thumbnail then. It's why we want to use the export server. Data is too big with the official server unfortunately.

**Comment by mcharnet** [comment]
Yes I do, but I need the legend on this chart actually. This is the main one, displayed as svg on the application (we need interactivity). It's on the exported one, as an image thumbnail, that we want to hide the legend.

**Comment by jakubSzuminski** [comment]
Thanks! So, doesn't this [demo](https://jsfiddle.net/BlackLabel/swvaLz4e/) show how to achieve that?

1. You use Highcharts to create a chart on your website
2. The chart has a legend
3. When exporting the chart, the chart has no legend

Isn't that what you were looking for?

**Comment by mcharnet** [comment]
Ah sorry, I forgot to mention that we want to export it too with the dedicated button, and with the legend... It's only on the thumbnail, obtained by a manual call to the export server, that we don't want it.

**Comment by jakubSzuminski** [comment]
Okay, I understand now.

Unfortunately, there's no easy way to achieve this for now if you have to send an SVG to the Export Server.

Alternatively you could send a JSON chart config to the Export Server and get a brand new chart with no legend. You could draw custom elements with the `Highcharts.SVGRenderer` ([API](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer)) if you wish to.

**Comment by mcharnet** [comment]
OK, thank you for your time ! I'll make some tries :)

**Comment by jakubSzuminski** [comment]
No problem! Do not hesitate to ask in case any more questions arise.
