### ISSUE TITLE
Sankey Support? 

### ISSUE THREAD

**Issue by RaulP11** [highcharts/node-export-server#423]
Hi I'm trying to use the sankey on the export server but I keep getting  : 

[error] - [export] Error encountered during export: Error: Evaluation failed: TypeError: Cannot destructure property 'chartHeight' of 'window.Highcharts.charts[0]' as it is undefined.

Is Sankey not supported ? or am I missing something? 

Thanks!

**Comment by RaulP11** [comment]
Thanks Jakub! I'm using the 2.1 version using Puppeteer Sorry I should have posted this better! 

Here is the config I'm using. I've tried setting the height everywhere ( as you can see ) but still getting the  message : 

{   'b64': True,
    'constr': 'Chart',
    'height': 100,
    'infile': '{"title": {"text": null}, 
              "plotOptions": {}, "tooltip": {"backgroundColor": "#434348", 
              "useHTML": true, "shadow": false}, "chart": {"marginLeft": 200, 
              "marginRight": 200, "height": 100, "chartHeight": 100}, 
              "options": {"chart": {"height": 200}}, "exporting": 
              {"sourceWidth": 700, "sourceHeight": 400, "scale": 1}, 
              "series": {"keys": ["from", "to", "weight"], "data": [["Barrow 'Robert", "Mind Meds", 1]], "zIndex": 999, "type": 
              "sankey", "colors": ["#5fbf4e", "#6f65d8", "#9ab635", ], "dataLabels": {"allowOverlap": true, 
              "useHTML": true, "align": "left", "color": "#000"}}}',
    'scale': 3,
    'type': 'image/png',
    'width': 200}

 [error] - [export] Error encountered during export: Error: Evaluation failed: TypeError: Cannot destructure property 'chartHeight' of 'window.Highcharts.charts[0]' as it is undefined.
Unable to process the chart, please check your input data.

**Comment by jakubSzuminski** [comment]
The problem is the following: `window.Highcharts.charts[0]` cannot be destructured because the chart was not created (because there a JavaScript error occurs during the creation of the chart).

The error stems from the fact that your `series` is not an array, but an object.

As you can see in the **[API](https://api.highcharts.com/highcharts/series)**, the `series` passed to the config needs to be an array.

This small change fixed it for me. Please let me know if that works for you as well.

---
**Demo with your config** not working: https://jsfiddle.net/BlackLabel/0tcn5f3p/
**Demo with a fix**: https://jsfiddle.net/BlackLabel/cnqd5fje/

**Comment by jakubSzuminski** [comment]
No problem! We're here to help. Do not hesitate to ask in case you have any more questions in the future.
