### ISSUE TITLE
Access to fetch at 'https://export.highcharts.com/' from origin 'https://.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

### ISSUE THREAD

**Issue by deepak626k** [highcharts/node-export-server#594]
#### Expected behaviour

Access to fetch at 'https://export.highcharts.com/' from origin 'https://.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
        
       POST https://export.highcharts.com/ net::ERR_FAILED 403 (Forbidden)
#### Actual behaviour

should work as expected
#### Affected browser(s)
<img width="532" alt="image" src="https://github.com/user-attachments/assets/b55480e1-a3e8-4d1f-a6b9-d9de1f48f2d1">

**Comment by hubertkozik** [comment]
Hi @deepak626k!

Thank you for reaching out regarding the issue with export.highcharts.com. Our export service is primarily designed to convert rendered charts into image files, typically initiated through the export menu attached to charts, in a browser window.

To ensure optimal performance for all users, we require that each request includes an identifiable referrer and user agent header. Requests missing these headers may be blocked by our system, so please verify that your requests include them.

Please note that due to the variability of traffic, there are no fixed limits on our service. Limits fluctuate in real time based on current traffic, complexity, and system load. Automated traffic—such as from bots, cron jobs, and event-driven processes—is given the lowest priority and may be restricted without prior warning when system load demands it.

If you're making automated or high-frequency requests, they may be subject to throttling or temporary restrictions. We recommend adjusting your usage accordingly.

If you continue to experience issues after verifying your headers and usage patterns, and that your usage aligns with [our guidelines](https://www.highcharts.com/docs/export-module/privacy-disclaimer-export). For further inquiries, feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), where our support engineers will help you.
