### ISSUE TITLE
Allow setting directory for async downloads

### ISSUE THREAD

**Issue by jacobweber** [highcharts/node-export-server#74]
When you pass "async" in a request to the HTTP server, it puts the files in the /tmp directory. I'd like to be able to specify a different directory. I tried --tmpdir, but that didn't affect it.

**Comment by cvasseng** [comment]
The `-tmpdir` option should now properly set the temporary directory when running as a server too.

Do let me know if you're still having problems.

**Comment by KacperMadej** [comment]
It seems that there's still a problem with `-tmpdir`. Maybe because variable is sometimes given as [`tmpDir`](https://github.com/highcharts/node-export-server/blob/bcc7676c57f5c5746934fb255f97c09c2e814e4d/lib/server.js#L60) ([2](https://github.com/highcharts/node-export-server/blob/bcc7676c57f5c5746934fb255f97c09c2e814e4d/lib/server.js#L407)) and sometimes as [`tmpdir`](https://github.com/highcharts/node-export-server/blob/bcc7676c57f5c5746934fb255f97c09c2e814e4d/lib/server.js#L220) ([2](https://github.com/highcharts/node-export-server/blob/bcc7676c57f5c5746934fb255f97c09c2e814e4d/lib/server.js#L308))

**Comment by cvasseng** [comment]
It's case sensitive, and should be all lower case.

**Comment by cvasseng** [comment]
Ah, yes this may cause issues in some node versions (not all of them allows referencing undefined variables like that; `tmpdir` was a typo). I've fixed it in 149a199.

As a side note, the folder that's specified must exist, and must be accessible by the user running the server.

**Comment by gian-luca1416** [comment]
Does it work with every node version?
So when I reinstall the export server it should work? Or can I simply change the typo in the file?

**Comment by KacperMadej** [comment]
@gian-luca1416 
The NPM packed is not yet published with the fix - please try with the code from this github repository.
If a simple change won't help please try with reinstalling.

**Comment by cvasseng** [comment]
This is pushed to npm, so if you're still having issues after reinstalling, please reopen this issue or create a new one.
